{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-ui-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-ui-role
subjects:
- kind: ServiceAccount
  name: {{ include "comax-rpui.serviceAccountName" . }}
  namespace: system
{{- end }}
