apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "comax-orchestrator.secretName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "comax-orchestrator.serviceAccountName" . }}
data:
  OIDC__Secret: {{ .Values.oidc.secret | b64enc }}
