{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-ui-role
rules:
- apiGroups:
  - communaxiom.org
  resources:
  - reverseproxies
  verbs:
  - '*'
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "comax-orchestrator.serviceAccountName" . }}
  labels:
    {{- include "comax-orchestrator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-ui-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-ui-role
subjects:
- kind: ServiceAccount
  name: {{ include "comax-orchestrator.serviceAccountName" . }}
  namespace: system