apiVersion: v1
kind: Service
metadata:
  name: {{ include "comax-rpui.fullname" . }}
  labels:
    {{- include "comax-rpui.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "comax-rpui.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{.Values.service.loadBalancerClass}}
  {{- end }}
