// <auto-generated />
using System;
using ComaxRpUI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComaxRpUI.Migrations
{
    [DbContext(typeof(RpDbContext))]
    [Migration("20230227035409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ComaxRpUI.Models.RpEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ForwardAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IngressCertManager")
                        .HasColumnType("longtext");

                    b.Property<string>("IngressCertSecret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IngressHost")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("UseHttps")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "LookupIndex")
                        .IsUnique();

                    b.HasIndex(new[] { "IngressHost" }, "UKHost")
                        .IsUnique();

                    b.ToTable("RpEntries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
